Repository opensourcecommunity-hub/developer-portfolios, pull requests merged in 2022-08, with the labels that each got.

#24 Improving the cards design
  website/package-lock.json
  website/package.json
  website/src/App.js
  website/src/index.css
Labels: SSOC, beginner, approved

#27 Added a portfolio template
  website/src/data.json
Labels: SSOC, intermediate, approved

#28 Implemented the dark mode
  website/package-lock.json
  website/package.json
  website/public/index.html
  website/src/App.js
  website/src/Toggle.js
  website/src/index.css
Labels: SSOC, beginner, approved

#32 Resolved texts are outside when hovering
  website/src/App.js
  website/src/index.css
Labels: SSOC, beginner, approved

#41 attribute key error resolved.
  website/src/App.js
Labels: SSOC, beginner, approved

#43 Customized Scroll bar
  website/package-lock.json
  website/package.json
  website/src/index.css
Labels: SSOC, beginner

#48 Added my portfolio
  package-lock.json
  website/src/data.json
Labels: SSOC, advanced, approved

#54 Added header section for issue #49
  website/src/App.js
  website/src/index.css
Labels: enhancement, frontend, advanced, approved

#55 fixed bug #issue 52
  .pnpm-debug.log
  website/pnpm-lock.yaml
  website/src/App.js
  website/src/index.css
Labels: bug, SSOC, intermediate, approved

#58 Added my portfolio website
  website/src/data.json
Labels: SSOC, beginner, approved

#60 Ifechi
  website/package.json
  website/pnpm-lock.yaml
  website/src/App.js
  website/src/components/Header.jsx
  website/src/components/Navbar.jsx
  website/src/components/Projects.jsx
  website/src/components/Toggle.jsx
  website/src/index.css
Labels: SSOC, advanced, approved
